# Generated by Django 4.2.30 on 2026-08-15 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caracter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hanzi', models.CharField(db_index=True, max_length=4, unique=True)),
                ('pinyin', models.CharField(blank=True, max_length=64)),
                ('definicion', models.TextField(blank=True)),
                ('radical', models.CharField(blank=True, max_length=4)),
                ('descomposicion', models.CharField(blank=True, max_length=64)),
                ('nivel_hsk', models.PositiveSmallIntegerField(blank=True, db_index=True, help_text='Nivel HSK. Null si el carácter no está en ninguna lista oficial.', null=True)),
                ('frecuencia', models.PositiveIntegerField(blank=True, help_text='Posición en listas de frecuencia. Menor = más común.', null=True)),
            ],
            options={
                'ordering': ['nivel_hsk', 'frecuencia', 'hanzi'],
            },
        ),
        migrations.CreateModel(
            name='Trazo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secuencia', models.PositiveSmallIntegerField(help_text='Orden de escritura, empezando en 1.')),
                ('path_svg', models.TextField(help_text='Contorno del trazo. Sistema de 1024x1024 con eje Y invertido.')),
                ('mediana', models.JSONField(default=list, help_text='Puntos de la línea central. Se compara contra el trazo del usuario.')),
                ('caracter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trazos', to='caracteres.caracter')),
            ],
            options={
                'ordering': ['secuencia'],
                'unique_together': {('caracter', 'secuencia')},
            },
        ),
    ]
