# Generated by Django 4.2.30 on 2026-08-15 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SesionEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_id', models.UUIDField()),
                ('nivel_hsk', models.PositiveSmallIntegerField()),
                ('dificultad', models.PositiveSmallIntegerField()),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('activa', 'Activa'), ('completada', 'Completada')], default='borrador', max_length=20)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('duracion_estimada_min', models.PositiveSmallIntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caracter', models.CharField(max_length=8)),
                ('tipo', models.CharField(choices=[('trazo', 'Orden de trazos'), ('pinyin', 'Reconocer pinyin'), ('significado', 'Significado')], max_length=20)),
                ('dificultad', models.PositiveSmallIntegerField()),
                ('es_refuerzo', models.BooleanField(default=False, help_text='True si nace de un error previo del usuario, no de contenido nuevo.')),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios', to='tutor.sesionestudio')),
            ],
        ),
    ]
