# Generated by Django 4.2.30 on 2026-08-15 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejercicio',
            name='fue_correcto',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='respondido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='respondido_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
