# Generated by Django 4.2.30 on 2026-09-03 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caracteres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_id', models.PositiveIntegerField(db_index=True)),
                ('nivel_hsk', models.PositiveSmallIntegerField()),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-creada_en'],
            },
        ),
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('trazo', 'Orden de trazos'), ('significado', 'Significado')], max_length=16)),
                ('completado', models.BooleanField(default=False)),
                ('caracter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios', to='caracteres.caracter')),
                ('leccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios', to='lecciones.leccion')),
            ],
        ),
    ]
