# Generated by Django 4.2.30 on 2026-08-15 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProgresoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_id', models.UUIDField(unique=True)),
                ('nivel_hsk', models.PositiveSmallIntegerField(default=1, help_text='Nivel en el que está practicando actualmente.')),
                ('nivel_max_desbloqueado', models.PositiveSmallIntegerField(default=1, help_text='Nivel más alto al que tiene acceso.')),
                ('tasa_acierto', models.FloatField(default=0.5, help_text='Proporción de respuestas correctas, de 0.0 a 1.0.')),
                ('caracteres_dominados', models.JSONField(blank=True, default=list, help_text='Lista de caracteres que ya no necesitan repaso frecuente.')),
                ('errores_frecuentes', models.JSONField(blank=True, default=dict, help_text='Mapa carácter -> número de veces que se falló.')),
                ('proximo_repaso', models.DateTimeField(blank=True, null=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Progreso de usuario',
                'verbose_name_plural': 'Progresos de usuarios',
            },
        ),
    ]
