# Generated by Django 4.2.30 on 2026-08-15 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progreso', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='progresousuario',
            name='aciertos_consecutivos',
            field=models.JSONField(blank=True, default=dict, help_text='Mapa carácter -> aciertos seguidos. Alimenta el repaso espaciado.'),
        ),
        migrations.AddField(
            model_name='progresousuario',
            name='agenda_repaso',
            field=models.JSONField(blank=True, default=dict, help_text='Mapa carácter -> fecha ISO del próximo repaso.'),
        ),
        migrations.AlterField(
            model_name='progresousuario',
            name='proximo_repaso',
            field=models.DateTimeField(blank=True, help_text='El más cercano de la agenda. Permite consultar sin abrir el JSON.', null=True),
        ),
    ]
